site_name: IIT Bombay Racing Team
theme:
  name: readthedocs
  highlightjs: true
  features:
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: false
      video_autoplay: True
      video_loop: True
  - search
nav:
    - Home: index.md
    - Goal 2024: goal.md
    # - Competition 101: competition.md
    - Key dates: dates.md
    - How to guides: howto.md
    - Weekly priorities: updates.md

    - Perception:
      - Overview: perception/overview.md

    - Estimation:  
      - Overview: estimation/overview.md
      - EKF SLAM: estimation/ekf_slam.md
      # - MRPT: estimation/mrpt.md

    - Path Planning and Controls:
      - Overview: controls/overview.md
      - Path Planning: controls/planning.md
      - Controls: controls/controls.md

    - System integation:
      - Overview: sysint/overview.md
      - CAN: sysint/can.md
      - Docker: sysint/docker.md